astrid/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework import routers

from dashboard import views


router = routers.DefaultRouter()
#router.register(r'users', views.UserViewSet)
#router.register(r'groups', views.GroupViewSet)
router.register(r'logs', views.LogViewSet)

urlpatterns = [
    #path('k8events/', views.k8events),
    path('healthCheck/', views.healthCheck),
    path('oidc/', include('mozilla_django_oidc.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('',views.welcome),
]

dashboard/urls.py
from django.urls import path
from django.contrib.auth.models import User

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('agreements/', views.agreements, name='agreements'),
    path('services/<int:service_id>/', views.service, name='service'),
    path('services/<int:service_id>/deploy', views.deploy, name='deploy'),
    path('editor/<int:service_id>/', views.editor, name="editor"),
    path('customize/<int:service_id>/', views.createSecurityPolicy, name="customize"),
    path('agent/', views.services, name="config"),
    path('agent/<slug:graph_id>/', views.configureAgent, name="config"),
    path('services/', views.services, name='services'),
    path('monitoring/', views.monitoring, name='monitoring'),
    path('logs/', views.logs, name='logs'),
    path('k8resource/', views.get_k8_resource, name="k8resource"),
    path('algorithm/', views.configureAlgorithm, name="algorithm"),
    # path('test/', views.start_test),
]

dashboard/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User

import uuid

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(blank=True)

    def __str__(self):
        return self.user.username


class Service(models.Model):
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    service_name = models.CharField(max_length=200)
    service_file = models.FileField(upload_to='uploads/')
    service_file_b64 = models.TextField(blank=True)
    service_file_orig_b64 = models.TextField(blank=True)
    graph_b64 = models.TextField(blank=True)
    last_modified = models.DateTimeField(auto_now=True)
    allowed_connections = models.TextField(blank=True)
    kibana_dashboard = models.TextField(blank=True)
    uuid = models.UUIDField(default=uuid.uuid4,editable=False)

    def __str__(self):
        return self.service_name


class SecurityPolicyTemplate(models.Model):
    BASIC = 'B'
    PRO = 'P'
    UNLIMITED = 'U'
    CUSTOM = 'C'
    SLA_CHOICES = (
        (BASIC, "Basic"),
        (PRO, "Pro"),
        (UNLIMITED, "Unlimited"),
        (CUSTOM, "Custom")
    )
    policy_sla = models.CharField(max_length=1,
                                  choices=SLA_CHOICES,
                                  default=BASIC)
    policy_name = models.CharField(max_length=200)
    policy_description = models.CharField(max_length=500)
    last_modified = models.DateTimeField(auto_now=True)
    policy_id = models.CharField(max_length=20,unique=True)
    code = models.TextField(blank=True)
    configuration = models.TextField(blank=True)
    
    def __str__(self):
        return self.policy_id


class SecurityPolicy(models.Model):
    BASIC = 'B'
    PRO = 'P'
    UNLIMITED = 'U'
    CUSTOM = 'C'
    SLA_CHOICES = (
        (BASIC, "Basic"),
        (PRO, "Pro"),
        (UNLIMITED, "Unlimited"),
        (CUSTOM, "Custom")
    )
    policy_sla = models.CharField(max_length=1,
                                  choices=SLA_CHOICES,
                                  default=BASIC)
    policy_name = models.CharField(max_length=200)
    policy_description = models.CharField(max_length=500)
    last_modified = models.DateTimeField(auto_now=True)
    policy_id = models.CharField(max_length=20)
    code = models.TextField(blank=True)
    configuration = models.TextField(blank=True)
    active = models.BooleanField(default=False)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    policy_uuid = models.UUIDField(default=uuid.uuid4,editable=False)
    service_file_b64 = models.TextField(blank=True)
    
    def __str__(self):
        return self.policy_id


class Log(models.Model):
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='logs',
        on_delete=models.CASCADE,
    )
    log_id = models.CharField(max_length=200)
    log_status = models.CharField(max_length=200)
    log_message = models.CharField(max_length=500)
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.log_id


class AgentTemplate(models.Model):
    name = models.CharField(max_length=200)
    agent_id = models.CharField(max_length=20,unique=True)
    partner = models.CharField(max_length=200, blank=True)
    description = models.CharField(max_length=500, blank=True)
    configuration = models.TextField(blank=True)
    image = models.CharField(max_length=200, blank=True)

    def __str__(self) -> str:
        return self.name


class Agent(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    agent_id = models.CharField(max_length=20)
    partner = models.CharField(max_length=200, blank=True)
    description = models.CharField(max_length=500, blank=True)
    configuration = models.TextField(blank=True)
    uuid = models.UUIDField(default=uuid.uuid4,editable=False)
    image = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.name


class AlgorithmTemplate(models.Model):
    name = models.CharField(max_length=200)
    algorithm_id = models.CharField(max_length=20,unique=True)
    partner = models.CharField(max_length=200, blank=True)
    description = models.CharField(max_length=500, blank=True)
    configuration = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Algorithm(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    algorithm_id = models.CharField(max_length=20)
    partner = models.CharField(max_length=200, blank=True)
    description = models.CharField(max_length=500, blank=True)
    configuration = models.TextField(blank=True)
    uuid = models.UUIDField(default=uuid.uuid4,editable=False)
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.algorithm_id

dashboard/forms.py
from django import forms

class UploadFileForm(forms.Form):
    # title = forms.CharField(max_length=50)
    file = forms.FileField()


class CubebeatForm(forms.Form):
    enabled = forms.BooleanField(label='Enabled', help_text='Enable/disable the collection of synflood data')
    period = forms.CharField(label='Period', help_text='Period to collect the synflood data')
    service_id = forms.IntegerField(widget=forms.HiddenInput())
    name = forms.CharField(widget=forms.HiddenInput())
    partner = forms.CharField(widget=forms.HiddenInput())


class AlgorithmForm(forms.Form):
    window = forms.CharField(label='Time window', help_text='Time window for batch processing')
    service_id = forms.IntegerField(widget=forms.HiddenInput())
    name = forms.CharField(widget=forms.HiddenInput())
    partner = forms.CharField(widget=forms.HiddenInput())

dashboard/views.py
import re
import json
import base64
import pickle
import bios
import urllib
import uuid
import copy
from itertools import chain

from kubernetes import config, client

from urllib.parse import urlparse

from django.urls import resolve, reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404, HttpResponseRedirect, HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate
from django.contrib.auth import login as django_login
from django.contrib.auth import logout as django_logout
from django.core.files.storage import default_storage
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.core.serializers.json import DjangoJSONEncoder
from django.core import serializers

from django.contrib.auth.models import User, Group
from kubernetes.client import configuration
from rest_framework import viewsets
from rest_framework import permissions
from rest_framework import generics

from .serializers import UserSerializer, GroupSerializer, LogSerializer

from .service import generate_visjs_graph
from .models import Algorithm, Service, SecurityPolicy, SecurityPolicyTemplate, Log, Agent, AgentTemplate, AlgorithmTemplate
from .tasks import test, kubernetes_apply, kubernetes_get_pod, test_echo, security_apply_policy
from .forms import CubebeatForm, AlgorithmForm

sc = {'name': 'astrid-agent', 'image': 'busybox', 'command': ['/bin/sh'], 'args': ['-c','while true; do sleep 5; done']}


@csrf_exempt
def healthCheck(request):
    return HttpResponse(status=200)


def get_k8_resource(request):
    namespace = request.GET.get('namespace', None)
    label = request.GET.get('label', None)
    print(f'{namespace} {label}')

    # s = json.loads(label)
    # selector = ','.join([f'{k}={s[k]}' for k in s])

    response = {}

    try:
        config.load_incluster_config()

        aApiClient = client.ApiClient()
        v1 = client.CoreV1Api(aApiClient)

        res = v1.list_namespaced_pod(namespace)

        j = {}
        for item in res.items:
            d = item.to_dict()
            if label in [c['name'] for c in d['spec']['containers']]:
                j = {"host_ip": d["status"]["host_ip"], 
                    "pod_ip": d["status"]["pod_ip"], 
                    "phase": d["status"]["phase"], 
                    "start_time": d["status"]["start_time"], 
                    "containers": [{"name": status["name"],
                                    "ready": status["ready"]} for status in d["status"]["container_statuses"]]}

            response = json.dumps(j, cls=DjangoJSONEncoder)
    except:
        pass

    return JsonResponse(response, safe=False)


# @csrf_exempt
# def start_test(request):
#     if request.method == 'GET':
#         test_echo()
#     return HttpResponse(status=200)


@csrf_exempt
def k8events(request):
    u = User.objects.filter(username='system')

    if not u:
        u = User.objects.create_user('system', 'system@astrid.local', 'system')
    else:
        u = User.objects.get(username='system')
    try:
        s = json.loads(request.body)
        if s["reason"] == "Started":
            if s["involvedObject"]["kind"] == "Pod":
                pod_name = s["involvedObject"]["name"]
                pod_namespace = s["involvedObject"]["namespace"]

                t = kubernetes_get_pod.delay(pod_name, pod_namespace)
                l = Log(owner=u, log_id=t.id, log_status=t.status)
                l.save()
    except Exception as ex:
        print(ex)

    return HttpResponse(status=200)


@login_required
def deploy(request, service_id):

    service = get_object_or_404(
        Service, id=service_id, owner_id=request.user.id)

    namespace = service.service_name
    yaml_b64 = service.service_file_b64
    enabled_policies = SecurityPolicy.objects.all().filter(service=service,active=True)
    enabled_algorithms = Algorithm.objects.all().filter(service=service,active=True)

    algorithms = [
        {
            "id": a.uuid,
            "name": a.name,
            "arguments": []

        } for a in enabled_algorithms]

    pipelines = [
        {
            "id": p.policy_uuid,
            "name": p.policy_name,
            "status": "started",
            "agents": [],
            "algorithms": algorithms,
            "configuration": p.configuration
        } for p in enabled_policies]

    sc = {
        "deployment": {
            "id": service.uuid,
            "name": service.service_name,
            "namespace": service.service_name,
            "pipelines": pipelines
        }
    }

    orchestrator = request.POST.get('orchestratorSelect', None)

    print(f"Deploy via {orchestrator} at {namespace}")
    print(sc)
        
    if orchestrator == "kubernetes":
        t = kubernetes_apply.delay(yaml_b64, namespace, sc)
        l = Log(owner=request.user, log_id=t.id,
                log_message=f"watching {namespace}", log_status=t.status)
        l.save()

    return redirect(reverse('dashboard:service', kwargs={'service_id': service_id}))

@login_required
def logs(request):
    # t = test.delay("hello")
    # l = Log(owner=request.user, log_id=t.id, log_status=t.status)
    # l.save()
    logs_list = Log.objects.filter()

    return render(request, 'dashboard/logs.html',
                  {'logs_list': logs_list})


@login_required
def createSecurityPolicy(request, service_id):
    if request.method == 'POST':
        # policy, created = SecurityPolicy.objects.update_or_create(
        #     policy_sla = 'C',
        #     policy_name = 'Custom-' + str(uuid.uuid4()),
        #     policy_description = "custom security service",
        #     policy_id = 'ASTRID_5555'
        # )
        # service = Service.objects.get(id=service_id, owner_id=request.user.id)
        # service.policies.add(policy)
        # service.save()
        pass

    return redirect(reverse('dashboard:service', kwargs={'service_id': service_id}))


@login_required
def configureAlgorithm(request):
    context = {}
    if request.method == 'POST':
        print(request.POST)
        algorithm_id = request.POST.get('id', 'ASTRID_9999')
    
    algorithm_id = 'ASTRID_9999'
    algorithm = AlgorithmTemplate.objects.get(algorithm_id=algorithm_id)
    form = AlgorithmForm()

    context = {"algorithm": algorithm, "form": form}
        
    return render(request, 'dashboard/algorithm.html', context)


@login_required
def configureAgent(request, graph_id):
    context = {}
    # if request.method == 'POST':
    #     print(request.POST)
    #     conf_str = json.dumps(request.POST)
    #     print(conf_str)

    #     service_id = request.POST.get('service_id', None)
    #     name = request.POST.get('name', None)
    #     partner = request.POST.get('partner', None)

    #     service = Service.objects.get(id=service_id, owner_id=request.user.id)

    #     agent, created = Agent.objects.update_or_create(
    #         service = service,
    #         graph_id = graph_id,
    #         name = name,
    #         partner = partner,
    #         defaults={'config': conf_str},
    #     )

    #     return redirect(reverse('dashboard:editor', kwargs={'service_id': service_id}))

    agent = Agent.objects.get(uuid=graph_id)
    print(agent)
    
    graph = pickle.loads(base64.b64decode(agent.service.graph_b64))
    nodes = graph['nodes']
    edges = graph['edges']

    # print(nodes)
    # print(edges)

    agents = AgentTemplate.objects.all()
    algorithms = AlgorithmTemplate.objects.all()

    context = {'nodes': nodes, 'edges': edges,
               'service': agent.service,
               'agents': agents, 'algorithms': algorithms,
               'agent': agent}

    return render(request, 'dashboard/editor.html', context)


@login_required
def editor(request, service_id):
    service = Service.objects.get(id=service_id, owner_id=request.user.id)
    pipeline = None
    if request.method == 'POST':
        data = None
        try:
            data = json.loads(request.body)
            print(data)
        except Exception as e:
            print("ERROR")
            print(e)

        yaml_b64 = service.service_file_b64
        yaml_file = pickle.loads(base64.b64decode(yaml_b64))
        print(yaml_file)

        if data:
            for d in data:
                if d["connections"]:
                    for y in yaml_file:
                        if not 'annotations' in y['metadata']:
                            continue
                        if y['metadata']['annotations']['graphId'] == d['id']:
                            for c in d["connections"]:
                                at = AgentTemplate.objects.get(name=c)
                                a = Agent(
                                    service=service,
                                    name=at.name,
                                    agent_id=at.agent_id,
                                    partner=at.partner,
                                    description=at.description,
                                    configuration=at.configuration,
                                    image=at.image
                                )
                                a.save()
                                container = {'image': a.image, 'name': a.name,
                                             'volumeMounts': [
                                                 {"name": "packetbeat",
                                                  "mountPath": "/etc/packetbeat/packetbeat.yml",
                                                  "subPath": "packetbeat.yml"
                                                 }
                                             ]
                                            } #, 'args': ['sleep', '1000']}
                                y["spec"]["template"]["spec"]["containers"].append(container)

dashboard/templates/dashboard/_dashboard.html
{% extends "_base.html" %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.1/css/all.css">
<!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/vis/4.21.0/vis.min.css" crossorigin="anonymous"> -->
<!-- Custom styles for this template -->
<link rel="stylesheet" href="{% static 'dashboard/css/dashboard.css' %}">
{% endblock style %}
{% block content %}
<header>
  <nav class="navbar fixed-top flex-md-nowrap p-0">
    <span class="navbar-brand col-sm-3 col-md-2 mr-0">A S T R I D</span>
    <ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        <a class="nav-link" href="{% url 'dashboard:logout' %}"><i class="fas fa-sign-out-alt"></i> Sign out</a>
      </li>
    </ul>
  </nav>
</header>

<main role="main" class="container-fluid">
<!-- <div class="container-fluid"> -->
  <div class="row">
    <div class="col-md-2">
      <!-- <nav class="col-md-2 d-none d-md-block bg-light sidebar"> -->
      <nav class="sidebar">
        <div>
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard:welcome' %}">
                <i class="fas fa-table"></i>
                Dashboard
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard:agreements' %}">
                <i class="fas fa-award"></i>
                Service-level agreements
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard:services' %}">
                <i class="fas fa-bezier-curve"></i>
                Services
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard:monitoring' %}">
                <i class="fas fa-chart-bar"></i>
                Monitoring
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <i class="fas fa-user"></i>
                User
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard:logs' %}">
                <i class="fas fa-clipboard-list"></i>
                Logs
              </a>
            </li>
          </ul>

          <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Help</span>
            <!-- <a class="d-flex align-items-center text-muted" href="#">
            <span data-feather="plus-circle"></span>
            </a> -->
          </h6>
          <ul class="nav flex-column mb-2">
            <li class="nav-item">
              <a class="nav-link" href="#">
                <i class="fab fa-readme"></i>
                Upload service description
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <i class="fab fa-readme"></i>
                Security enrichment
              </a>
            </li>
          </ul>
        </div>
      </nav>
    </div>

    <div class="col ml-2 mt-2">
    <!-- <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4"> -->
    {% block main %}
    {% endblock main %}
    </div>
    <!-- </main> -->
  <!-- </div> -->
  </div>
</main>
{% block footer %}
<!-- <div id="footer" class="row"> -->
  <!-- <footer class="pt-4 my-md-5 pt-md-5 border-top"> -->
  <!-- <footer class="col-md-9 ml-sm-auto col-lg-10 border-top fixed-bottom"> -->
<footer class="footer pt-4">
  <div class="container">
    <div class="row">
    <div class="col-12 col-md">
      <img class="mb-2" src="{% static 'dashboard/img/astrid-logo.png' %}" alt="">
      <small class="d-block mb-3 text-muted">&copy; 2018-2021</small>
    </div>
    <div class="col-6 col-md">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Security enrichment</a></li>
        <li><a class="text-muted" href="#">Service deployment</a></li>
        <li><a class="text-muted" href="#">ASTRID developers</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Project</a></li>
        <li><a class="text-muted" href="#">Papers</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>About</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Team</a></li>
        <li><a class="text-muted" href="#">Privacy</a></li>
        <li><a class="text-muted" href="#">Terms</a></li>
      </ul>
    </div>
  </div>
  </div>
</footer>
<!-- </div> -->
{% endblock footer %}
{% endblock content%}
{% block script %}
<script type="text/javascript" src="https://unpkg.com/vis-network/standalone/umd/vis-network.min.js"></script>
{% endblock %}

dashboard/templates/dashboard/config.html
{% extends "dashboard/_dashboard.html" %}
{% load static %}

{% block main %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h2>Security enrichment pipeline editor</h2>
</div>
<div class = "row">
  <h2 class="col">Namespace: {{ agent.service.service_name }}</h2>
</div>
<!-- <div class="row">
  <p class="col"><i class="fas fa-info-circle"></i> Click to add a new ASTRID Agent</p>
</div> -->
<form action="{% url 'dashboard:config' agent.graph_id %}" method="POST">
{% csrf_token %}
<div class="row">
  <div class="col-4">
    <p>Agent: {{ agent.name }}</p>
    <p>Partner: {{ agent.partner }}</p>
    <p>Id: {{ agent.graph_id }}</p>
  </div>
  <div class="col">
      <p>Configuration</p>
      {{ form.as_p }}
  </div>
</div>
<div class="row mb-5">
  <div class="col-4">
    <button id="saveAgent" type="submit" class="btn btn-danger">Save</button>
  </div>
</div>
</form>

<!-- {% csrf_token %} -->
{% endblock %}
{% block customjs %}
{% endblock %}

dashboard/templates/dashboard/index.html
{% extends "dashboard/dashboard.html" %}
{% load static %}

{% block main %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
<h1 class="display-4">Welcome!</h1>
<p class="lead">What you can do</p>
</div>

<div class="container">
  <div class="card-deck">
    <div class="card">
      <a href="{% url 'dashboard:services' %}">
      <img src="{% static 'dashboard/img/cloud-upload-alt-solid.svg' %}" class="card-img-top mt-3" alt="" style="height:60px">
      </a>
      <div class="card-body">
        <h5 class="card-title">Upload service description</h5>
        <p class="card-text">Upload your service description file (TOSCA, Docker-Compose <i class="fab fa-docker"></i>)</p>
      </div>
      <div class="card-footer">
        <!-- <small class="text-muted">Last updated 3 mins ago</small> -->
      </div>
    </div>
    <div class="card">
      <a href="{% url 'dashboard:services' %}">
      <img src="{% static 'dashboard/img/bezier-curve-solid.svg' %}" class="card-img-top mt-3" alt="" style="height:60px">
      </a>
      <div class="card-body">
        <h5 class="card-title">Apply security enrichment</h5>
        <p class="card-text">Select security enrichments according to your SAL</p>
      </div>
      <div class="card-footer">
        <!-- <small class="text-muted">Last updated 3 mins ago</small> -->
      </div>
    </div>
    <div class="card">
      <a href="{% url 'dashboard:services' %}">
      <img src="{% static 'dashboard/img/cogs-solid.svg' %}" class="card-img-top mt-3" alt="" style="height:60px">
      </a>
      <div class="card-body">
        <h5 class="card-title">Deploy secured service</h5>
        <p class="card-text">Deploy your secured service with supported service orchestrators</p>
      </div>
      <div class="card-footer">
        <!-- <small class="text-muted">Last updated 3 mins ago</small> -->
      </div>
    </div>
    <div class="card">
      <img src="{% static 'dashboard/img/chart-bar-solid.svg' %}" class="card-img-top mt-3" alt="" style="height:60px">
      <div class="card-body">
        <h5 class="card-title">Monitor service</h5>
        <p class="card-text">Monitoring, alerting, trending (MAT), analytics of your secured services</p>
      </div>
      <div class="card-footer">
        <!-- <small class="text-muted">Last updated 3 mins ago</small> -->
      </div>
    </div>
  </div>
</div>

{% endblock %}

dashboard/templates/dashboard/welcome.html
{% extends "dashboard/_dashboard.html" %}
{% load static %}

{% block main %}
<!-- <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center"> -->
<div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
<h1 class="display-4">Welcome!</h1>
<p class="lead">What you can do</p>
</div>

<div class="container">
  <div class="card-deck">
    <div class="card">
      <a href="{% url 'dashboard:services' %}">
      <img src="{% static 'dashboard/img/cloud-upload-alt-solid.svg' %}" class="card-img-top mt-3" alt="" style="height:60px">
      </a>
      <div class="card-body">
        <h5 class="card-title">Upload service description</h5>
        <p class="card-text">Upload your service description file</p>
      </div>
      <!-- <div class="card-footer">
        <small class="text-muted">Last updated 3 mins ago</small>
      </div> -->
    </div>
    <div class="card">
      <a href="{% url 'dashboard:services' %}">
      <img src="{% static 'dashboard/img/bezier-curve-solid.svg' %}" class="card-img-top mt-3" alt="" style="height:60px">
      </a>
      <div class="card-body">
        <h5 class="card-title">Apply security enrichment</h5>
        <p class="card-text">Select security enrichments according to your SLA</p>
      </div>
      <!-- <div class="card-footer">
        <small class="text-muted">Last updated 3 mins ago</small>
      </div> -->
    </div>
    <div class="card">
      <a href="{% url 'dashboard:services' %}">
      <img src="{% static 'dashboard/img/cogs-solid.svg' %}" class="card-img-top mt-3" alt="" style="height:60px">
      </a>
      <div class="card-body">
        <h5 class="card-title">Deploy secured service</h5>
        <p class="card-text">Deploy your secured service with supported service orchestrators</p>
      </div>
      <!-- <div class="card-footer">
        <small class="text-muted">Last updated 3 mins ago</small>
      </div> -->
    </div>
    <div class="card">
      <a href="{% url 'dashboard:monitoring' %}">
      <img src="{% static 'dashboard/img/chart-bar-solid.svg' %}" class="card-img-top mt-3" alt="" style="height:60px">
      </a>
      <div class="card-body">
        <h5 class="card-title">Monitor service</h5>
        <p class="card-text">Monitoring, alerting, trending (MAT), analytics of your secured services</p>
      </div>
      <!-- <div class="card-footer">
        <small class="text-muted">Last updated 3 mins ago</small>
      </div> -->
    </div>
  </div>
</div>

{% endblock %}